name: generate swagger docs
on: 
  pull_request:
    paths:
      - 'docs/**'
jobs:
  generate-docs:
    name: generate Swagger doc
    runs-on: ubuntu-latest
    steps:
      - name: Check out code directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node(for Redoc)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: generate docs
        run: |
          cd docs
          npx redoc-cli bundle sample.yaml
      
      - name: commit generated docs
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "generate Redoc from swagger.yaml"
          git push origin HEAD:${GITHUB_HEAD_REF}
