name: generate from Swagger.yaml
on:
  push:
    paths:
      - "docs/**"
jobs:
  generate-docs:
    name: generate from Swagger.yaml
    runs-on: ubuntu-latest
    steps:
      - name: Check out code directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node(for Redoc)
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: git initialize
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: generate docs
        run: |
          cd docs
          npx redoc-cli bundle sample.yaml

      - name: commit generated docs
        run: |
          if (git diff --shortstat | grep '[0-9]'); then
            git add .
            git commit -m "generate Redoc from swagger.yaml"
          fi

      - name: generate go model
        run: |
          . third_party/bin/go-swagger generate model --spec=./docs/sample.yaml

      - name: commit generated go model
        run: |
          if (git diff --shortstat | grep '[0-9]'); then
            git add .
            git commit -m "generate Redoc from go model"
          fi

      - name: push
        run: |
          git push
